AWSTemplateFormatVersion: "2010-09-09"
Description: Basic EC2 instance

Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t3.micro"  # Free tier instance
      ImageId: "ami-08eb150f611ca277f"  # Example for ubuntu (update for your region)
      KeyName: "devops"  # Replace with your actual key pair
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd php php-mysqlnd
          service httpd start
          chkconfig httpd on
          cd /var/www/html
          wget https://wordpress.org/latest.tar.gz
          tar -xzf latest.tar.gz
          cp -r wordpress/* .
          rm -rf wordpress latest.tar.gz
          mv wp-config-sample.php wp-config.php
          sed -i "s/database_name_here/devwordpressdb/" wp-config.php
          sed -i "s/username_here/admin/" wp-config.php
          sed -i "s/password_here/devpassword/" wp-config.php

Outputs:
  InstanceId:
    Description: "EC2 Instance ID"
    Value: !Ref MyEC2Instance
  PublicIp:
    Description: "Public IP address of the instance"
    Value: !GetAtt MyEC2Instance.PublicIp

